{"name": "test_filter_error_recovery", "status": "passed", "description": "Test filter error recovery mechanisms.", "start": 1751312149703, "stop": 1751312149703, "uuid": "93a1c275-f9b8-4665-9b71-836d590cb87b", "historyId": "c6667c265872afe1e0e389eee8ac753e", "testCaseId": "c6667c265872afe1e0e389eee8ac753e", "fullName": "unit.test_filter_unit.TestFilterCore#test_filter_error_recovery", "labels": [{"name": "tag", "value": "pyramid_unit"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "unit"}, {"name": "suite", "value": "test_filter_unit"}, {"name": "subSuite", "value": "TestFilterCore"}, {"name": "host", "value": "fealfr"}, {"name": "thread", "value": "30472-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "unit.test_filter_unit"}]}